[package]
name = "aptos-vote-protocol"
version = "0.0.1"
authors = ["MilanoM"]

[addresses]
vote = "0xCAFE"
tests = "0xC0FFEE"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework" }
